name: 'Run runn'
description: 'GitHub Action for runn, a tool for api scenario testing.'
branding:
  icon: 'octagon'
  color: 'gray-dark'
inputs:
  version:
    description: Specify runn version
    required: false
    default: 'v0.82.0'
  command:
    description: run or list or loadt
    required: true
    default: 'run'
  path_pattern:
    description: Path pattern
    required: true
  debug:
    description: Filter runbooks to be executed
    required: false
    default: false
  verbose:
    description: Verbose mode
    required: false
    default: false
  fail-fast:
    description: Fail fast mode
    required: false
    default: false
  skip-test:
    description: Skip test mode
    required: false
    default: false
  shuffle:
    description: Shuffle mode
    required: false
    default: false
  concurrent:
    description: Concurrent mode
    required: false
    default: false
runs:
  using: 'composite'
  steps:
  - name: 'Check input parameter'
    shell: 'bash'
    if: inputs.version
    run: |
      if [[ "${{ inputs.version }}" < "v0.64.0" ]]; then
        echo "Error: runn version ${{ inputs.version }} is not supported. Please use v0.64.0 or higher."
        exit 1
      fi
  - name: 'Run runn'
    uses: 'docker://ghcr.io/k1low/runn:${{ inputs.version }}'
    with:
      args:
        - ${{ inputs.command }}
        - ${{ inputs.path_pattern }}
        - ${{ (inputs.debug == 'true' && '--debug') || '' }}
        - ${{ (inputs.verbose == 'true' && '--verbose') || '' }}
        - ${{ (inputs.fail-fast == 'true' && '--fail-fast') || '' }}
        - ${{ (inputs.skip-test == 'true' && '--skip-test') || '' }}
        - ${{ (inputs.shuffle == 'true' && '--shuffle on') || '' }}
        - ${{ (inputs.concurrent == 'true' && '--concurrent on') || '' }}
