name: 'Run runn'
description: 'GitHub Action for runn, a tool for api scenario testing.'
branding:
  icon: 'octagon'
  color: 'gray-dark'
inputs:
  command:
    description: run or list or loadt
    required: true
    default: 'run'
  path_pattern:
    description: Path pattern
    required: true
  debug:
    description: Filter runbooks to be executed
    required: false
    default: false
  verbose:
    description: Verbose mode
    required: false
    default: false
  fail-fast:
    description: Fail fast mode
    required: false
    default: false
  skip-test:
    description: Skip test mode
    required: false
    default: false
  shuffle:
    description: Shuffle mode
    required: false
    default: false
  concurrent:
    description: Concurrent mode
    required: false
    default: false    
runs:
  using: 'docker'
  image: 'docker://ghcr.io/k1low/runn:v0.72.0'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.path_pattern }}
    - ${{ (inputs.debug == 'true' && '--debug') || '' }}
    - ${{ (inputs.verbose == 'true' && '--verbose') || '' }}
    - ${{ (inputs.fail-fast == 'true' && '--fail-fast') || '' }}
    - ${{ (inputs.skip-test == 'true' && '--skip-test') || '' }}
    - ${{ (inputs.shuffle == 'true' && '--shuffle on') || '' }}
    - ${{ (inputs.concurrent == 'true' && '--concurrent on') || '' }}
